[package]
name = "flake"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
nomercy-core = { path = "../nomercy-core" }
serde.workspace = true
